name: Build Lesis Engine
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Engine
        run: |
          cl.exe /O2 /MT /EHsc lesis_engine.cpp /Fe:LesisEngine.exe /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LesisEngine-Exe
          path: LesisEngine.exe
