name: Build Lesis Engine
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Verify Files
        run: dir  # Bu komut klasördeki dosyaları listeleyecek
      - name: Compile Engine
        run: |
          cl.exe /O2 /MT /EHsc lesis_engine.cpp /Fe:LesisEngine.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LesisEngine-Exe
          path: LesisEngine.exe
